/* =========================================================================================
   SCRIPT 2 - INSERT DATA
   Client:   Palo Alto UHNW Client
   Schema:   paloalto_client
   Author:   Juanjo Chiarella
   Course:   Data Management & SQL - DAT 5486
   Date:     June 2026

   This script inserts all static data into the dimension and fact tables.
   Run this AFTER script1.

   Order of execution (respects FK dependencies):
   1. dim_client
   2. dim_ticker
   3. fct_holdings
   4. fct_daily_ror  (populated in script3 — after pricing data is loaded)

   Note: fct_pricing_daily is loaded separately using the file:
         data/pricing_inserts.sql (generated by generate_sql_from_csv.py)
========================================================================================= */

USE paloalto_client;


/* -----------------------------------------------------------------------------------------
   dim_client
   Our client is an Ultra High Net Worth individual based in Palo Alto, CA.
   Total liquid assets: $95 million.
   customer_id is AUTO_INCREMENT so we do not specify it here — starts at 1.
----------------------------------------------------------------------------------------- */
INSERT INTO paloalto_client.dim_client (full_name, location, total_aum_usd)
VALUES ('Juanjo Chiarella', 'Palo Alto, CA', 95000000.00);


/* -----------------------------------------------------------------------------------------
   dim_ticker
   5 portfolio tickers + 3 benchmark tickers.
   is_benchmark = 0 for portfolio holdings, 1 for benchmarks.
   SPY = US equity benchmark
   AGG = US fixed income benchmark
   VT  = Global equity benchmark (relevant because IXN is global tech)
----------------------------------------------------------------------------------------- */

-- portfolio holdings
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('IXN', 'iShares Global Tech ETF',              'Equity',        0);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('QQQ', 'Invesco NASDAQ 100 ETF',               'Equity',        0);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('IEF', 'iShares 7-10 Year Treasury Bond ETF',  'Fixed Income',  0);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('VNQ', 'Vanguard Real Estate ETF',             'Real Assets',   0);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('GLD', 'SPDR Gold Shares',                     'Commodities',   0);

-- benchmark tickers
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('SPY', 'SPDR S&P 500 ETF',                     'Equity',        1);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('AGG', 'iShares Core US Aggregate Bond ETF',   'Fixed Income',  1);
INSERT INTO paloalto_client.dim_ticker (ticker, ticker_name, asset_class, is_benchmark)
VALUES ('VT',  'Vanguard Total World Stock ETF',       'Equity',        1);


/* -----------------------------------------------------------------------------------------
   fct_holdings
   Portfolio allocation as provided by the professor.
   allocation_pct is stored as decimal (0.1750 = 17.5%).
   value_usd = allocation_pct x 95,000,000.
   customer_id = 1 (the only client we registered above).
   Benchmarks are NOT included here — they are not holdings.
----------------------------------------------------------------------------------------- */
INSERT INTO paloalto_client.fct_holdings (customer_id, ticker, allocation_pct, value_usd)
VALUES (1, 'IXN', 0.1750, 16625000.00);
INSERT INTO paloalto_client.fct_holdings (customer_id, ticker, allocation_pct, value_usd)
VALUES (1, 'QQQ', 0.2210, 20995000.00);
INSERT INTO paloalto_client.fct_holdings (customer_id, ticker, allocation_pct, value_usd)
VALUES (1, 'IEF', 0.2850, 27075000.00);
INSERT INTO paloalto_client.fct_holdings (customer_id, ticker, allocation_pct, value_usd)
VALUES (1, 'VNQ', 0.0890,  8455000.00);
INSERT INTO paloalto_client.fct_holdings (customer_id, ticker, allocation_pct, value_usd)
VALUES (1, 'GLD', 0.2300, 21850000.00);


/* =========================================================================================
   VALIDATION
========================================================================================= */

-- verify client was inserted
SELECT * FROM paloalto_client.dim_client;

-- verify all 8 tickers were inserted (5 portfolio + 3 benchmarks)
SELECT ticker, ticker_name, asset_class,
       CASE WHEN is_benchmark = 1 THEN 'Benchmark' ELSE 'Portfolio' END AS ticker_type
FROM paloalto_client.dim_ticker
ORDER BY is_benchmark, asset_class;

-- verify holdings add up to 100% and $95M
SELECT
    COUNT(*)                        AS num_holdings,
    SUM(allocation_pct)             AS total_allocation_pct,
    SUM(value_usd)                  AS total_value_usd
FROM paloalto_client.fct_holdings;

-- verify each holding detail
SELECT
    h.ticker,
    td.ticker_name,
    td.asset_class,
    h.allocation_pct * 100          AS allocation_pct,
    h.value_usd
FROM paloalto_client.fct_holdings h
JOIN paloalto_client.dim_ticker td ON h.ticker = td.ticker
ORDER BY h.allocation_pct DESC;
